#!/bin/bash

declare -i clocklow=800000 #Clock minimo para cpu rodar
declare -i clockhigh=2000000 #Maximo que a cpu pode chegar
declare -i numerocpu=4 #Começa contar de 0 o numero de nucleos

AUTODADOS(){
    cpufreq-info > cpu.info
    numerocpu=$(cpufreq-info | grep -c "limites") # -c conta o numero de linhas no grep / FUNCIONANDO
    IN=$(cpufreq-info -l)
    frequencias=$(echo $IN | tr " " "\n")
    declare -i contador=0
    for clocks in $frequencias
    do
      echo "> $clocks"
      if [ $contador = 0 ]
      then
          contador+=1
          clocklow=$clocks
      else
          clockhigh=$clocks-1400000 #editar a partir daqui
      fi
    done
}

GETDADOS(){ #NEVER USED YET
	numerocpu=$(zenity --entry --text "Digite o numero de Threads de sua CPU: (Ex: 2, 4, 8)" --title "cpuinfo-auto")
	clocklow=$(zenity --entry --text "Digite o clock minimo desejado: (Ex: 800mhz)" --title "cpuinfo-auto")
	clockhigh=$(zenity --entry --text "Digite o clock maximo desejado: (Ex: 2500mhz)" --title "cpuinfo-auto")
}

CPU(){
	declare -i countercpu=0
	declare -i counterlimite=$numerocpu-1
	while [ $countercpu -le $counterlimite ]; do
		cpufreq-set -c $countercpu -d $clocklow
		cpufreq-set -c $countercpu -u $clockhigh
		countercpu+=1
	done
}

MAIN(){
	AUTODADOS
	CPU
}

MAIN
